name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello gitub action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Shrenik"
